# Generated by Django 3.0.6 on 2020-08-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='activity_periods',
            field=models.DateTimeField(max_length=240),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
