# Generated by Django 3.0.6 on 2020-08-09 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20200809_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='activity_periods',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='tz',
            field=models.CharField(default='Europe/London', max_length=60),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.User_data')),
            ],
        ),
    ]
